apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  labels:
    app: my-app
spec:
  type: LoadBalancer  # Use NodePort for local clusters (like Minikube)
  selector:
    app: my-app
  ports:
  - protocol: TCP
    port: 80          # Port exposed by the service
    targetPort: 80    # Port on the container
